menu:
  home: /
  archives: /archives
  tags: /tags

favicon: /favicon.ico


# Code Highlight theme
## Available value: normal | night | night eighties | night blue | night bright
## https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

# Specify the date when the site was setup
since: 2013

version: 0.0.5